import translations from "@/config/food-ui-copy.json";
import { localeDirection, resolveLocale } from "@/lib/locales";

export type FoodUiCopy = typeof translations.en;

export function getFoodUi(value?: string | null) {
  const locale = resolveLocale(value);
  return {
    locale,
    direction: localeDirection(locale),
    copy: translations[locale as keyof typeof translations] ?? translations.en,
  };
}

export function formatFoodUi(template: string, values: Record<string, string | number>): string {
  // Replace template token occurrences in one pass. Product text remains literal even when
  // it contains braces, dollar signs or words used by the UI catalogue.
  return template.replace(/\{([a-zA-Z]+)\}/g, (token, key: string) =>
    Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : token);
}

const statusKeys = Object.keys(translations.en).filter(key => key.startsWith("status")) as (keyof FoodUiCopy)[];
const statusLookup = new Map(statusKeys.map(key => [translations.en[key], key]));

export function translateFoodStatus(message: string, copy: FoodUiCopy): string {
  // These exact messages are generated by our existing request controller.
  // No locale enters its state, request keys, effects or callback dependencies.
  // Never translate provider data, arbitrary server text or product descriptions.
  const key = statusLookup.get(message);
  return key ? copy[key] : message;
}

export function countRecordedGrades(items: ReadonlyArray<{ nutri_score?: string | null }>) {
  const grades = ["A", "B", "C", "D", "E"].map(grade => ({ grade, count: 0 }));
  let known = 0;
  for (const item of items) {
    const grade = grades.find(entry => entry.grade === item.nutri_score?.toUpperCase());
    if (grade) { grade.count += 1; known += 1; }
  }
  return { grades, known, total: items.length, missing: items.length - known };
}

const recordedGradeColors: Record<string, { backgroundColor: string; color: string }> = {
  A: { backgroundColor: "#038141", color: "#ffffff" },
  B: { backgroundColor: "#85bb2f", color: "#17211a" },
  C: { backgroundColor: "#fecb02", color: "#17211a" },
  D: { backgroundColor: "#ee8100", color: "#17211a" },
  E: { backgroundColor: "#c9382a", color: "#ffffff" },
};

export function recordedGradeStyle(grade?: string | null) {
  const key = grade?.trim().toUpperCase();
  return key && /^[A-E]$/.test(key) ? recordedGradeColors[key] : undefined;
}
