import translations from "@/config/food-ui-copy.json";
import { localeDirection, resolveLocale } from "@/lib/locales";

export type FoodUiCopy = typeof translations.en;

export function getFoodUi(value?: string | null) {
  const locale = resolveLocale(value);
  return {
    locale,
    direction: localeDirection(locale),
    copy: translations[locale as keyof typeof translations] ?? translations.en,
  };
}

export function formatFoodUi(template: string, values: Record<string, string | number>): string {
  // Replace template token occurrences in one pass. Product text remains literal even when
  // it contains braces, dollar signs or words used by the UI catalogue.
  return template.replace(/\{([a-zA-Z]+)\}/g, (token, key: string) =>
    Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : token);
}

const statusKeys = Object.keys(translations.en).filter(key => key.startsWith("status")) as (keyof FoodUiCopy)[];
const statusLookup = new Map(statusKeys.map(key => [translations.en[key], key]));

export function translateFoodStatus(message: string, copy: FoodUiCopy): string {
  // These exact messages are generated by our existing request controller.
  // No locale enters its state, request keys, effects or callback dependencies.
  // Never translate provider data, arbitrary server text or product descriptions.
  const key = statusLookup.get(message);
  return key ? copy[key] : message;
}

/** Translate only the reference label generated by our backend, never package text. */
export function displayServingSize(value: string, copy: FoodUiCopy): string {
  return value === "100 g / 100 ml (source reference)" ? copy.sourceReference : value;
}

export function countRecordedGrades(items: ReadonlyArray<{ nutri_score?: string | null }>) {
  const grades = ["A", "B", "C", "D", "E"].map(grade => ({ grade, count: 0 }));
  let known = 0;
  for (const item of items) {
    const grade = grades.find(entry => entry.grade === item.nutri_score?.trim().toUpperCase());
    if (grade) { grade.count += 1; known += 1; }
  }
  return { grades, known, total: items.length, missing: items.length - known };
}

/** A visual mean of recorded product letters, not a new nutritional grade.
 * Each known entry counts once; missing grades and portion size add no weight.
 */
export function recordedGradePosition(summary: ReturnType<typeof countRecordedGrades>) {
  if (summary.known === 0) return null;
  const average = summary.grades.reduce((sum, entry, index) => sum + index * entry.count, 0) / summary.known;
  return {
    percent: average * 25,
    lower: summary.grades[Math.floor(average)].grade,
    upper: summary.grades[Math.ceil(average)].grade,
  };
}

const recordedGradeColors: Record<string, { backgroundColor: string; color: string }> = {
  A: { backgroundColor: "#038141", color: "#ffffff" },
  B: { backgroundColor: "#85bb2f", color: "#17211a" },
  C: { backgroundColor: "#fecb02", color: "#17211a" },
  D: { backgroundColor: "#ee8100", color: "#17211a" },
  E: { backgroundColor: "#c9382a", color: "#ffffff" },
};

export function recordedGradeStyle(grade?: string | null) {
  const key = grade?.trim().toUpperCase();
  return key && /^[A-E]$/.test(key) ? recordedGradeColors[key] : undefined;
}
